# Generated by Django 5.1.7 on 2025-04-27 11:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("slug", models.SlugField(unique=True, verbose_name="Slug URL")),
                ("excerpt", models.TextField(verbose_name="Extrait")),
                (
                    "content",
                    models.TextField(blank=True, null=True, verbose_name="Contenu"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="articles/", verbose_name="Image principale"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Publié"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de publication",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de mise à jour"
                    ),
                ),
            ],
            options={
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="Ebook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("slug", models.SlugField(unique=True, verbose_name="Slug URL")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "cover_image",
                    models.ImageField(
                        upload_to="ebooks/covers/", verbose_name="Image de couverture"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="ebooks/files/", verbose_name="Fichier PDF"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Position d'affichage"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de mise à jour"
                    ),
                ),
            ],
            options={
                "verbose_name": "E-book",
                "verbose_name_plural": "E-books",
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                ("role", models.CharField(max_length=100, verbose_name="Rôle")),
                (
                    "avatar",
                    models.ImageField(upload_to="testimonials/", verbose_name="Avatar"),
                ),
                ("quote", models.TextField(verbose_name="Citation")),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        default=5,
                        verbose_name="Note",
                    ),
                ),
            ],
            options={
                "verbose_name": "Témoignage",
                "verbose_name_plural": "Témoignages",
            },
        ),
        migrations.CreateModel(
            name="Training",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("slug", models.SlugField(unique=True, verbose_name="Slug URL")),
                (
                    "short_description",
                    models.TextField(verbose_name="Description courte"),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, null=True, verbose_name="Contenu détaillé"
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Durée"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Prix",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="trainings/", verbose_name="Image"),
                ),
                (
                    "video_url",
                    models.URLField(blank=True, null=True, verbose_name="URL Vidéo"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Position d'affichage"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de mise à jour"
                    ),
                ),
            ],
            options={
                "verbose_name": "Formation",
                "verbose_name_plural": "Formations",
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="EbookDownload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Prénom")),
                ("last_name", models.CharField(max_length=100, verbose_name="Nom")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Téléphone"
                    ),
                ),
                (
                    "consent_mailing",
                    models.BooleanField(
                        default=False, verbose_name="Consent pour emailing"
                    ),
                ),
                (
                    "download_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de téléchargement"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Adresse IP"
                    ),
                ),
                (
                    "ebook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="downloads",
                        to="api_app.ebook",
                        verbose_name="E-book",
                    ),
                ),
            ],
            options={
                "verbose_name": "Téléchargement E-book",
                "verbose_name_plural": "Téléchargements E-books",
            },
        ),
        migrations.CreateModel(
            name="Paragraph",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, null=True, verbose_name="Contenu du paragraphe"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="paragraphs/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True,
                        help_text="YouTube ou Vimeo URL",
                        null=True,
                        verbose_name="URL Vidéo",
                    ),
                ),
                (
                    "video_file",
                    models.FileField(
                        blank=True,
                        help_text="Téléchargez directement un fichier vidéo (recommandé < 100 MB)",
                        null=True,
                        upload_to="paragraph_videos/",
                        verbose_name="Fichier Vidéo",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="paragraph_thumbnails/",
                        verbose_name="Miniature vidéo",
                    ),
                ),
                (
                    "file_size_mb",
                    models.FloatField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="Taille du fichier (MB)",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(default=0, verbose_name="Position"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de mise à jour"
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paragraphs",
                        to="api_app.article",
                        verbose_name="Article",
                    ),
                ),
                (
                    "training",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paragraphs",
                        to="api_app.training",
                        verbose_name="Formation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paragraphe",
                "verbose_name_plural": "Paragraphes",
                "ordering": ["position"],
            },
        ),
    ]
