# Generated by Django 5.1.7 on 2025-04-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paragraph",
            name="media_type",
            field=models.CharField(
                choices=[
                    ("none", "Aucun média"),
                    ("image", "Image"),
                    ("video_url", "Lien vidéo externe"),
                    ("video_file", "Fichier vidéo"),
                ],
                default="none",
                max_length=10,
                verbose_name="Type de média",
            ),
        ),
        migrations.AlterField(
            model_name="paragraph",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="Obligatoire pour les fichiers vidéo",
                null=True,
                upload_to="paragraph_thumbnails/",
                verbose_name="Miniature vidéo",
            ),
        ),
    ]
