# Generated by Django 5.1.7 on 2025-04-27 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_app", "0002_paragraph_media_type_alter_paragraph_thumbnail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="training",
            name="content",
        ),
    ]
