# Generated by Django 5.1.7 on 2025-04-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_app", "0003_remove_training_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="paragraph",
            name="title",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Titre"
            ),
        ),
    ]
