# Generated by Django 5.1.7 on 2025-04-28 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_app", "0005_training_show_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="authors/",
                        verbose_name="Photo",
                    ),
                ),
                (
                    "bio",
                    models.TextField(blank=True, null=True, verbose_name="Biographie"),
                ),
            ],
            options={
                "verbose_name": "Auteur",
                "verbose_name_plural": "Auteurs",
            },
        ),
        migrations.AddField(
            model_name="article",
            name="source_url",
            field=models.URLField(
                blank=True,
                help_text="URL du site d'origine si l'article est repris d'ailleurs",
                null=True,
                verbose_name="URL de la source",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="articles",
                to="api_app.author",
                verbose_name="Auteur",
            ),
        ),
    ]
