# Generated by Django 5.1.7 on 2026-03-17

from django.db import migrations, models


def create_default_rgpd_content(apps, schema_editor):
    RGPDContent = apps.get_model("api_app", "RGPDContent")
    if not RGPDContent.objects.exists():
        RGPDContent.objects.create(pk=1)


class Migration(migrations.Migration):

    dependencies = [
        ("api_app", "0006_author_article_source_url_article_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="RGPDContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "owner_name",
                    models.CharField(
                        default="Audrey Antonini",
                        max_length=150,
                        verbose_name="Nom de la responsable",
                    ),
                ),
                (
                    "trade_name",
                    models.CharField(
                        default="ImmoShift",
                        max_length=150,
                        verbose_name="Nom commercial",
                    ),
                ),
                (
                    "legal_status",
                    models.CharField(
                        default="Entreprise individuelle",
                        max_length=150,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "siret",
                    models.CharField(
                        default="503 425 027 00045",
                        max_length=20,
                        verbose_name="SIRET",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        default="12 les 4 canaux, 34250 Palavas-les-Flots",
                        max_length=255,
                        verbose_name="Adresse",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        default="immoshift.business@gmail.com",
                        max_length=254,
                        verbose_name="Email",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        default="0609093075",
                        max_length=20,
                        verbose_name="Téléphone",
                    ),
                ),
                (
                    "host_name",
                    models.CharField(
                        blank=True,
                        default="o2switch",
                        max_length=200,
                        verbose_name="Nom de l'hébergeur",
                    ),
                ),
                (
                    "host_address",
                    models.CharField(
                        blank=True,
                        default="Chemin des Pardiaux, 63000 Clermont-Ferrand, France",
                        max_length=255,
                        verbose_name="Adresse de l'hébergeur",
                    ),
                ),
                (
                    "host_contact",
                    models.CharField(
                        blank=True,
                        default="https://www.o2switch.fr/support-hebergeur/",
                        max_length=255,
                        verbose_name="Contact de l'hébergeur",
                    ),
                ),
                (
                    "personal_data_text",
                    models.TextField(
                        default="Les données personnelles collectées via le formulaire de contact et le formulaire de téléchargement des e-books (nom, prénom, email, téléphone) sont utilisées uniquement dans le cadre de la relation commerciale avec ImmoShift.\n\nLes prises de rendez-vous via Calendly sont gérées par ce service tiers et soumises à sa propre politique de confidentialité.\n\nConformément au RGPD, vous disposez d'un droit d'accès, de rectification et de suppression de vos données. Vous pouvez exercer ce droit en écrivant à immoshift.business@gmail.com.",
                        verbose_name="Texte données personnelles",
                    ),
                ),
                (
                    "cookies_text",
                    models.TextField(
                        default="Ce site utilise uniquement des cookies strictement nécessaires à son fonctionnement. Aucun cookie de suivi publicitaire n'est déposé.",
                        verbose_name="Texte cookies",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name="Dernière mise à jour",
                    ),
                ),
            ],
            options={
                "verbose_name": "RGPD",
                "verbose_name_plural": "RGPD",
            },
        ),
        migrations.RunPython(create_default_rgpd_content, migrations.RunPython.noop),
    ]
