# Generated by Django 5.1.7 on 2026-05-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_app", "0007_rgpdcontent"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        default="ImmoShift",
                        max_length=150,
                        verbose_name="Nom de l'entreprise",
                    ),
                ),
                (
                    "company_description",
                    models.TextField(
                        default="Formation pour agents immobiliers. Structurez votre activit�, ma�trisez vos m�thodes et performez durablement.",
                        verbose_name="Description de l'entreprise",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        default="immoshift.business@gmail.com",
                        max_length=254,
                        verbose_name="Email de contact",
                    ),
                ),
                (
                    "contact_address",
                    models.CharField(
                        default="Palavas-les-Flots, 34250, France",
                        max_length=255,
                        verbose_name="Adresse",
                    ),
                ),
                (
                    "contact_city",
                    models.CharField(
                        default="Palavas-les-Flots",
                        max_length=150,
                        verbose_name="Ville",
                    ),
                ),
                (
                    "linkedin_url",
                    models.URLField(
                        default="https://www.linkedin.com/in/audrey-a-26baa3205",
                        verbose_name="URL LinkedIn",
                    ),
                ),
                (
                    "calendly_url",
                    models.URLField(
                        default="https://calendly.com/audreyantonini13/45-minutes-pour-faire-le-point",
                        verbose_name="URL Calendly",
                    ),
                ),
                (
                    "calendly_title",
                    models.CharField(
                        default="R�server un appel d�couverte de 45 minutes",
                        max_length=200,
                        verbose_name="Titre Calendly",
                    ),
                ),
                (
                    "calendly_description",
                    models.TextField(
                        default="Cet appel 45 minutes est un rendez-vous professionnel de d�couverte et d'�change...\nIl s'adresse aux agents immobiliers qui veulent prendre de la hauteur sur leur activit� � que ce soit pour corriger ce qui coince, structurer ce qui grandit trop vite, ou optimiser ce qui fonctionne d�j�.\nOn parle de ton fonctionnement, de tes priorit�s, de tes points de friction ou de progression.\nJe t'�coute, je t'oriente.\nEt si je peux t'apporter de la valeur, je t'explique comment je peux t'accompagner.\nCe n'est pas une s�ance de coaching offerte, mais un premier contact cadr�, pour poser les bases d'un accompagnement sur mesure.",
                        verbose_name="Description d�taill�e Calendly",
                    ),
                ),
                (
                    "calendly_description_short",
                    models.TextField(
                        default="R�server un rendez-vous de 45 minutes pour discuter de vos besoins en formation immobili�re.",
                        verbose_name="Description courte Calendly",
                    ),
                ),
                (
                    "calendly_button_text",
                    models.CharField(
                        default="R�server Maintenant",
                        max_length=50,
                        verbose_name="Texte du bouton Calendly",
                    ),
                ),
                (
                    "hero_title",
                    models.CharField(
                        default="ImmoShift",
                        max_length=200,
                        verbose_name="Titre principal",
                    ),
                ),
                (
                    "hero_subtitle",
                    models.CharField(
                        default="VISION - POSTURE BUSINESS",
                        max_length=255,
                        verbose_name="Sous-titre",
                    ),
                ),
                (
                    "hero_description_1",
                    models.TextField(
                        default="Des formations professionnelles, � distance ou en pr�sentiel, pour replacer l'agent immobilier � son juste rang : celui d'un r�f�rent qu'on ne met plus en concurrence, parce qu'il tient une ma�trise visible et une conduite de vente sans flottement, du premier �change jusqu'� la signature.",
                        verbose_name="Description Paragraphe 1",
                    ),
                ),
                (
                    "hero_description_2",
                    models.TextField(
                        default="L'objectif : faire passer l'agent du statut \"interchangeable\" au statut d'�vidence avec une tenue commerciale solide, une parole qui engage, et une mani�re de mener chaque dossier qui am�ne vendeurs et acheteurs � s'aligner sur une strat�gie claire, sans test permanent, sans perte d'ascendant, et sans dilution du r�le.",
                        verbose_name="Description Paragraphe 2",
                    ),
                ),
                (
                    "hero_catchphrase",
                    models.CharField(
                        default="M�thode. Discipline. Ex�cution.",
                        max_length=200,
                        verbose_name="Phrase d'accroche",
                    ),
                ),
                (
                    "hero_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="site_images/",
                        verbose_name="Image de pr�sentation (ex: Audrey)",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Derni�re mise � jour"
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration du Site",
                "verbose_name_plural": "Configurations du Site",
            },
        ),
        migrations.RemoveField(
            model_name="article",
            name="content",
        ),
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="articles/",
                verbose_name="Image principale",
            ),
        ),
    ]
