# Generated by Django 5.1.7 on 2026-05-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_app", "0009_siteconfiguration_extra_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="navigation_links",
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="calendly_button_text",
            field=models.CharField(
                default="Réserver Maintenant",
                max_length=50,
                verbose_name="Texte du bouton Calendly",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="calendly_description",
            field=models.TextField(
                default="Cet appel 45 minutes est un rendez-vous professionnel de découverte et d'échange.\nIl s'adresse aux agents immobiliers qui veulent prendre de la hauteur sur leur activité — que ce soit pour corriger ce qui coince, structurer ce qui grandit trop vite, ou optimiser ce qui fonctionne déjà.\nOn parle de ton fonctionnement, de tes priorités, de tes points de friction ou de progression.\nJe t'écoute, je t'oriente.\nEt si je peux t'apporter de la valeur, je t'explique comment je peux t'accompagner.\nCe n'est pas une sênce de coaching offerte, mais un premier contact cadré, pour poser les bases d'un accompagnement sur mesure.",
                verbose_name="Description détaillée Calendly",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="calendly_description_short",
            field=models.TextField(
                default="Réserver un rendez-vous de 45 minutes pour discuter de vos besoins en formation immobilière.",
                verbose_name="Description courte Calendly",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="calendly_title",
            field=models.CharField(
                default="Réserver un appel découverte de 45 minutes",
                max_length=200,
                verbose_name="Titre Calendly",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="company_description",
            field=models.TextField(
                default="Formation pour agents immobiliers. Structurez votre activité, maîtrisez vos méthodes et performez durablement.",
                verbose_name="Description de l'entreprise",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="hero_catchphrase",
            field=models.CharField(
                default="Méthode. Discipline. Exécution.",
                max_length=200,
                verbose_name="Phrase d'accroche",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="hero_description_1",
            field=models.TextField(
                default="Des formations professionnelles, à distance ou en présentiel, pour replacer l'agent immobilier à son juste rang : celui d'un référent qu'on ne met plus en concurrence, parce qu'il tient une maîtrise visible et une conduite de vente sans flottement, du premier échange jusqu'à la signature.",
                verbose_name="Description Paragraphe 1",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="hero_description_2",
            field=models.TextField(
                default="L'objectif : faire passer l'agent du statut \"interchangeable\" au statut d'évidence avec une tenue commerciale solide, une parole qui engage, et une manière de mener chaque dossier qui amène vendeurs et acheteurs à s'aligner sur une stratégie claire, sans test permanent, sans perte d'ascendant, et sans dilution du rôle.",
                verbose_name="Description Paragraphe 2",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="hero_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="site_images/",
                verbose_name="Image de présentation (ex: Audrey)",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Dernière mise à jour"
            ),
        ),
    ]
